### ISSUE TITLE
word-simplification fails randomly

### ISSUE THREAD

**Issue by arcz** [ethereum/hevm#311]
The word-simplification test started failing probably after the witch changes. QC replay is also not reliable, could be due to https://github.com/ethereum/hevm/issues/300.
```
2023-07-12T08:41:36.4155530Z hevm> FAIL (0.69s)
2023-07-12T08:41:36.4155840Z hevm>       *** Failed! Falsified (after 7 tests and 1 shrink):
2023-07-12T08:41:36.4156270Z hevm>       -8
2023-07-12T08:41:36.4156620Z hevm>       Use --quickcheck-replay=58705 to reproduce.
2023-07-12T08:41:36.4157040Z hevm>       Use -p '/word-simplification/' to rerun this test only.
2023-07-12T08:41:36.4613330Z hevm>     readStorage-equivalance:                                      Unsat
```

**Comment by msooseth** [comment]
This has recently been fixed in a PR. Also, replayability has been fixed, in a separate PR, too. It had to do with unsafeInto, which caught a bug, yay! The branch that fixe3d it was called `fix-stripwrites-bug`. I am closing because I'm pretty sure it's fixed now :)

**Comment by arcz** [comment]
Hmm, looks like it still fails on main:
```
2023-07-12T09:55:28.0758970Z hevm> FAIL (0.08s)
2023-07-12T09:55:28.0759318Z hevm>       *** Failed! Falsified (after 8 tests):
2023-07-12T09:55:28.0759708Z hevm>       ZeroDepthWord (SHA256 (WriteWord (Lit 0x53) (Lit 0x28) (ConcreteBuf "++U\r\186\198\133\176k")))
2023-07-12T09:55:28.0760691Z hevm>       Use --quickcheck-replay=266145 to reproduce.
2023-07-12T09:55:28.0761261Z hevm>       Use -p '/word-simplification/' to rerun this test only.
```
https://github.com/ethereum/hevm/actions/runs/5530031614/jobs/10088891505

**Comment by msooseth** [comment]
Yeah... I tried fixing it with #313  but apparently, that run also triggered another fail. I am digging....

**Comment by msooseth** [comment]
Hm, so #313 fixes:

```
a = SHA256 (WriteWord (Lit 0x1) (Lit 0x0) (ConcreteBuf "1"))
b = Expr.simplify a
checkEquiv a b
```

but we still have:

```
a = Keccak (WriteWord (Lit 0x1) (Lit 0) (ConcreteBuf "1"))
b = Expr.simplify a
checkEquiv a b
```

Annoyingly similar.

**Comment by msooseth** [comment]
Actually #313 was something odd. Removing. So the above two are new bugs.

**Comment by msooseth** [comment]
This is a Z3 bug. Specifically `Z3 version 4.8.17 - 64 bit` reports UNSAT and so does CVC4. However newer Z3 reports SAT. Ooopps. Opening a Z3 issue now.

**Comment by arcz** [comment]
hmm, this is unfortunate. Should we downgrade to the previous version for now? or ignore the test?

**Comment by d-xo** [comment]
hm since the new version seems to be a lot faster, and the issue is a false positive rather than a false negative I would be inclined to stay on the new version. Do you have any thoughts @msooseth ?

**Comment by msooseth** [comment]
I don't know :( Sorry. I'll let you decide. It may take a while for a new Z3 version to come out that fixes the bug. OTOH maybe we should try moving to CVC5 default anyway :smiley:

**Comment by msooseth** [comment]
Reverted back to old Z3 so this is can be closed.
